//
// Created by 79612 on 23.05.2021.
//

#ifndef SPBETU_DYNAMICSYSTEMS_COURSEWORK_SESSION_H
#define SPBETU_DYNAMICSYSTEMS_COURSEWORK_SESSION_H


class Session {

};


#endif //SPBETU_DYNAMICSYSTEMS_COURSEWORK_SESSION_H
